SECRET = {}

SECRET['AWS_KEY'] = ''
SECRET['AWS_SECRET'] = ''
SECRET['SERVE_REMOTE'] = False
SECRET['BUCKET_CNAME'] = False

BULKDATA = {
    'AWS_KEY': SECRET['AWS_KEY'],
    'AWS_SECRET': SECRET['AWS_SECRET'],
    'AWS_BUCKET': '',
    'AWS_PREFIX': '',
}
