general_issue_codes = {
    "ACC": "Accounting",
    "ADV": "Advertising",
    "AER": "Aerospace",
    "AGR": "Agriculture",
    "ALC": "Alcohol & Drug Abuse",
    "ANI": "Animals",
    "APP": "Apparel/Clothing Industry/Textiles",
    "ART": "Arts/Entertainment",
    "AUT": "Automotive Industry",
    "AVI": "Aviation/Aircraft/Airlines",
    "BAN": "Banking",
    "BNK": "Bankruptcy",
    "BEV": "Beverage Industry",
    "BUD": "Budget/Appropriations",
    "CHM": "Chemicals/Chemical Industry",
    "CIV": "Civil Rights/Civil Liberties",
    "CAW": "Clean Air & Water (Quality)",
    "CDT": "Commodities (Big Ticket)",
    "COM": "Communications/Broadcasting/Radio/TV",
    "CPI": "Computer Industry",
    "CSP": "Consumer Issues/Safety/Protection",
    "CON": "Constitution",
    "CPT": "Copyright/Patent/Trademark",
    "DEF": "Defense",
    "DOC": "District of Columbia",
    "DIS": "Disaster Planning/Emergencies",
    "ECN": "Economics/Economic Development",
    "EDU": "Education",
    "ENG": "Energy/Nuclear",
    "ENV": "Environmental/Superfund",
    "FAM": "Family Issues/Abortion/Adoption",
    "FIR": "Firearms/Guns/Ammunition",
    "FIN": "Financial Institutions/Investments/Securities",
    "FOO": "Food Industry (Safety, Labeling, etc.)",
    "FOR": "Foreign Relations",
    "FUE": "Fuel/Gas/Oil",
    "GAM": "Gaming/Gambling/Casino",
    "GOV": "Government Issues",
    "HCR": "Health Issues",
    "HOM": "Homeland Security",
    "HOU": "Housing",
    "IMM": "Immigration",
    "IND": "Indian/Native American Affairs",
    "INS": "Insurance",
    "INT": "Intelligence and Surveillance",
    "LBR": "Labor Issues/Antitrust/Workplace",
    "LAW": "Law Enforcement/Crime/Criminal Justice",
    "MAN": "Manufacturing",
    "MAR": "Marine/Maritime/Boating/Fisheries",
    "MIA": "Media (Information/Publishing)",
    "MED": "Medical/Disease Research/Clinical Labs",
    "MMM": "Medicare/Medicaid",
    "MON": "Minting/Money/Gold Standard",
    "NAT": "Natural Resources",
    "PHA": "Pharmacy",
    "POS": "Postal",
    "RRR": "Railroads",
    "RES": "Real Estate/Land Use/Conservation",
    "REL": "Religion",
    "RET": "Retirement",
    "ROD": "Roads/Highway",
    "SCI": "Science/Technology",
    "SMB": "Small Business",
    "SPO": "Sports/Athletics",
    "TAR": "Miscellaneous Tariff Bills",
    "TAX": "Taxation/Internal Revenue Code",
    "TEC": "Telecommunications",
    "TOB": "Tobacco",
    "TOR": "Torts",
    "TRD": "Trade (Domestic & Foreign)",
    "TRA": "Transportation",
    "TOU": "Travel/Tourism",
    "TRU": "Trucking/Shipping",
    "URB": "Urban Development/Municipalities",
    "UNM": "Unemployment",
    "UTI": "Utilities",
    "VET": "Veterans",
    "WAS": "Waste (hazardous/solid/interstate/nuclear)",
    "WEL": "Welfare"
}

filing_types = {
    "REGISTRATION": "registration",
    "REGISTRATION AMENDMENT": "registration_amendment",

    "MID-YEAR TERMINATION (NO ACTIVITY)": 'termination',
    "YEAR-END TERMINATION (NO ACTIVITY)": 'termination',
    "YEAR-END TERMINATION": 'termination',
    "MID-YEAR TERMINATION": 'termination',
    "FOURTH QUARTER TERMINATION": 'termination',
    "SECOND QUARTER TERMINATION": 'termination',
    "FIRST QUARTER TERMINATION": 'termination',
    "FIRST QUARTER TERMINATION (NO ACTIVITY)": 'termination',
    "THIRD QUARTER TERMINATION": 'termination',
    "THIRD QUARTER TERMINATION (NO ACTIVITY)": 'termination',
    "FOURTH QUARTER TERMINATION (NO ACTIVITY)": 'termination',
    "SECOND QUARTER TERMINATION (NO ACTIVITY)": 'termination',

    "YEAR-END REPORT": 'report',
    "YEAR-END (NO ACTIVITY)": 'report',
    "MID-YEAR REPORT": 'report',
    "MID-YEAR (NO ACTIVITY)": 'report',
    "SECOND QUARTER REPORT": 'report',
    "FIRST QUARTER REPORT": 'report',
    "FOURTH QUARTER REPORT": 'report',
    "THIRD QUARTER REPORT": 'report',
    "SECOND QUARTER (NO ACTIVITY)": 'report',
    "FIRST QUARTER (NO ACTIVITY)": 'report',
    "FOURTH QUARTER (NO ACTIVITY)": 'report',
    "THIRD QUARTER (NO ACTIVITY)": 'report',

    "MID-YEAR AMENDMENT": 'report_amendment',
    "THIRD QUARTER AMENDMENT": 'report_amendment',
    "YEAR-END AMENDMENT": 'report_amendment',
    "YEAR-END AMENDMENT (NO ACTIVITY)": 'report_amendment',
    "FIRST QUARTER AMENDMENT": 'report_amendment',
    "FIRST QUARTER AMENDMENT (NO ACTIVITY)": 'report_amendment',
    "FOURTH QUARTER AMENDMENT": 'report_amendment',
    "SECOND QUARTER AMENDMENT": 'report_amendment',
    "SECOND QUARTER AMENDMENT (NO ACTIVITY)": 'report_amendment',
    "THIRD QUARTER AMENDMENT (NO ACTIVITY)": 'report_amendment',
    "FOURTH QUARTER AMENDMENT (NO ACTIVITY)": 'report_amendment',
    "MID-YEAR AMENDMENT (NO ACTIVITY)": 'report_amendment',

    "MID-YEAR TERMINATION AMENDMENT": 'termination_amendment',
    "MID-YEAR TERMINATION AMENDMENT (NO ACTIVITY)": 'termination_amendment',
    "YEAR-END TERMINATION AMENDMENT": 'termination_amendment',
    "YEAR-END TERMINATION AMENDMENT (NO ACTIVITY)": 'termination_amendment',
    "SECOND QUARTER TERMINATION AMENDMENT (NO ACTIVITY)":
        'termination_amendment',
    "FIRST QUARTER TERMINATION AMENDMENT (NO ACTIVITY)":
        'termination_amendment',
    "FIRST QUARTER TERMINATION AMENDMENT": 'termination_amendment',
    "SECOND QUARTER TERMINATION AMENDMENT": 'termination_amendment',
    "THIRD QUARTER TERMINATION AMENDMENT": 'termination_amendment',
    "THIRD QUARTER TERMINATION AMENDMENT (NO ACTIVITY)":
        'termination_amendment',
    "FOURTH QUARTER TERMINATION AMENDMENT (NO ACTIVITY)":
        'termination_amendment',
    "FOURTH QUARTER TERMINATION AMENDMENT": 'termination_amendment',

    "YEAR-END TERMINATION LETTER": 'termination_letter',
    "MID-YEAR TERMINATION LETTER": 'termination_letter',

    "MISC. DOC": 'misc_document',
    "MISC TERM": 'misc_termination',
}
